Ask LLM to remove `#include 'non-existent filepath` and suggest alternatives (#403)
LLM insists on including non-existent files, likely because LLM _thinks_
that's necessary (for the function-under-test) or does not know what's
the correct alternatives
```
isc_lex_gettoken.c:5:10: fatal error: 'isc/boolean.h' file not found
    5 | #include <isc/boolean.h>
      |          ^~~~~~~~~~~~~~~
```

This PR specifically asks LLM to remove that incorrect statement (and
suggest any existent alternatives).