Fix priming for fixing on OpenAI models. (#121)
There was a confusion between the priming text and the priming prompt.
It is not a problem for text prompts where the role is ignored, but for
structured prompts (OpenAI), we got into a state where the structured
prompt was a nested structure:

```json
{
  "role": "system",
  "content": [
    {
      "role": "system",
      "content": "Given the following C++ program and its build error message, fix the code to achieve the original functionality.\n\nIf a function is missing, fix it by including the related libraries.\n\nIf the error contains \"undefined reference to\", this means one or more of the header <code>#include</code> directives need to be wrapped with <code>extern \"C\" {}</code> for the object linking to succeed. You must fix this by rewriting the relevant <code>#include</code> and wrapping it with <code>extern \"C\" {}</code>.\n"
    }
  ]
}
```

Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>