Set back temperature to 0.4 (#527)
This PR:
1. Sets back the default temperature to 0.4.
2. Continues #448 to allow different temperatures for fuzz target
samples.

 I will re-run a full exp to validate their effect.

The recent [08-03
report](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-03-weekly-all/)
contains regressions due to model inadequacies, such as:
```c++
fuzz/parse.cc:13:21: error: calling 'parse_url<url>' with incomplete return type 'url'
   13 |   ada::url result = ada::parser::parse_url(url, base_url);
```

This is likely because we [increased the
temperature](https://github.com/google/oss-fuzz-gen/pull/448/files#diff-0d648b28bb6b85213eb0ff1c3954edd4b710ff8b219eb7dc89b294108dfedb3eL52-R52).
Maybe code generation needs to be more strict and less random?

Also #448 did not pass `VARY_TEMPERATURE` to `run_all_experiments.py`,
this PR fixes that and support it in PR experiments.